### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by kequach** [amacanovic/KeynessMeasures#1]
Hello, I saw that this repository currently has no license attached. Did you maybe miss this or was this something you planned to add at a later stage (for example discussing appropriate license)? Technically, no one is allowed to reuse these resources if no license is given. If you need some help with this I'd be happy to assist.

**Comment by amacanovic** [comment]
Hello, thank you for pointing this out!
We were intensely working on improving the code and the documentation; so the current version was not licensed ahead of those changes. 
Still, since those will take a while longer, I have now added full license information; the code in this project is subject to the GPL-3.0 license. I hope this helps!
